---
- hosts: all
  gather_facts: False
  tasks:
    # gathers facts and registers the output as `ec2_facts`
    - name: Gather EC2 facts.
      ec2_remote_facts:
      region: "{{ region | default(us-west-2) }}"
      register: ec2_facts

    # debug that output
    - name: Display Debug Message when Verbosity is set to 2
      debug:
        msg: "{{ aws_ec2_facts }}"
        verbosity: 2
