---
- hosts: all
  gather_facts: False
  tasks:
      - name: Generate Dynamic Groups based upon the instance KEY_NAMEs
        group_by:
           key: "{{ ec2_key_name }}"

- hosts: "{{ pattern | default('all') }}"
  gather_facts: False
  roles: 
    - role: get_aws_facts
