---
# Quick and dirty way of setting a passed in username/password across multiple 
# servers. Use  --extra-vars "usr=USER pattern=KEY_NAME" when calling the playbook.
# 
# Prior to using, insert hash value of desired password in appropriate location
# generate hash (after installing passlib) by using the command below:
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
#
# To fully automate, package this into a role
- hosts: all
  gather_facts: False
  tasks:
    - name: Generate Dynamic Groups based upon the instance KEY_NAMEs
      group_by: 
         key: "{{ ec2_key_name }}"
      
- hosts: "{{ pattern | default('all') }}"
  tasks:
    - name: Ensure user exist with particular password
      user:
        name: "{{ usr }}"
        state: present 
        update_password: always 
        password: $6$rounds=656000$w91nghiFOmpdEEPE$sHJWfEbgT9a/IC18Ec4ID4N5WnbDkjp5y6uaORBjuWv9O07DQVLVY18oIzzs6oBaKhzNoRhQsbgtHK1qC2FOT.
        shell: /bin/bash
