---
- hosts: all
  gather_facts: False
  tasks:
      - name: Generate Dynamic Groups based upon the instance KEY_NAMEs
        group_by:
           key: "{{ ec2_key_name }}"

- hosts: "{{ pattern | default('all') }}"

- include: change_aws_usr_passwds
