---
- hosts: all
  tasks:
    - name: Gather facts from Remote hosts
      ec2_facts:
        validate_certs: no
      register: ec2Facts
      
    - debug:
        var: ec2Facts
        verbosity: 2
      
