---

#  name: Stop sandbox instances
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'ansible_crtd_inst'
      - 'ansible_crtd_inst_01'
    region: us-west-2
  tasks:
    - name: Stop the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
