---
 - name: Provision EC2 Box
   local_action:
     module: ec2
     key_name: "{{ key_name }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ region }}"
     instance_tags: '{"Name":"{{tag_Name}}","Type":"{{tag_Type}}","Environment":"{{tag_Environment}}"}'
     assign_public_ip: yes
     wait: true
     count: 1
#     volumes: 
#     - device_name: /dev/sda1
#       device_type: gp2
#       volume_size: "{{ ec2_volume_size }}"
#       delete_on_termination: true
   register: ec2

 - debug: var=item
   with_items: ec2.instances

 - add_host: name={{ item.public_ip }} >
             groups=tag_Type_{{tag_Type}},tag_Environment_{{tag_Environment}}
             ec2_region={{region}} 
             ec2_tag_Name={{tag_Name}}
             ec2_tag_Type={{tag_Type}}
             ec2_tag_Environment={{ag_Environment}}
             ec2_ip_address={{item.public_ip}}
   with_items: ec2.instances

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
   with_items: ec2.instances
