---

# gathers facts and registers the output as `ec2_facts`
- name: Gather EC2 facts.
  ec2_remote_facts:
    region: "us-west-2"
  register: ec2_facts

# debug that output
- name: Display Debug Message when Verbosity is set to 2
  debug:
    var: "{{ ec2_facts }}"
    verbosity: 2

